name: "Update a GCR image based on new file changes"
description: "Authenticate with gcloud, build (using previous build if it can), and push image to GCR"
author: "Nicholas Gronow <nick@wov.io>"
branding:
  icon: "arrow-up-circle"
  color: "green"
inputs:
  check_if_changed:
    description: "Checks if working_directory has changed since the previous commit"
    required: false
    default: "true"
  working_directory:
    description: "Directory we want to perform the build on"
    required: false
    default: .
  dockerfile:
    description: "Path to the dockerfile"
    required: false
    default: Dockerfile
  registry:
    description: "GCP Registry (e.g. 'gcr.io')"
    required: false
    default: gcr.io
  project:
    description: "GCP project name"
    required: true
  image:
    description: "Image name. Defaults to repo name if not provided (without github username)"
    required: false
  image_tag:
    description: "Image tag. Image will also be tagged with commit sha"
    required: false
    default: latest
  build_args:
    description: "Pass a list of env vars as build-args for docker-build, separated by commas"
    required: false
  service_key:
    description: "Your GCP service key with storage admin permission in json format"
    required: true
runs:
  using: "docker"
  image: "docker://nickgronow/deploy-to-gcr:latest"
