name: "Update a GCR image based on new file changes"
description: "Authenticate with gcloud, pull previous build, build using previous build cache, and push image to GCR"
author: "Nicholas Gronow <nick@wov.io>"
branding:
  icon: "arrow-up-circle"
  color: "green"
inputs:
  check_if_changed:
    description: "Checks if working_directory has changed since the previous commit"
    required: false
    default: "true"
  working_directory:
    description: "Directory where the Dockerfile is to be found"
    required: false
    default: /
  registry:
    description: "GCP Registry (e.g. 'gcr.io')"
    required: false
    default: gcr.io
  project:
    description: "GCP project name"
    required: true
  image_name:
    description: "Image name"
    required: true
  image_tag:
    description: "Image tag. Image will also be tagged with commit sha"
    required: false
with:
  service_key: {{ secrets.gcp_service_key }}
runs:
  using: "docker"
  image: "docker://passionkind/github-action-cloud-run:latest"
